project_id = "adrucmfpqonloiydooqy"

[functions.predict-price-ai]
verify_jwt = false

[functions.cargo-split]
verify_jwt = false

[functions.route-optimize]
verify_jwt = false

[functions.document-verify]
verify_jwt = false

[functions.demand-forecast]
verify_jwt = false

[functions.revenue-forecast]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.recommend-containers]
verify_jwt = false

[functions.notify-high-utilization]
verify_jwt = false

[functions.delay-prediction]
verify_jwt = false

[functions.predict-weather]
verify_jwt = false
